spring.application.name=content-spark-backend
server.port=8080

# Gemini API Configuration
spring.config.import=optional:classpath:secrets.properties
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
